main:
- name: Blog
  pageRef: /blog/
  weight: 10
- name: Portafolio
  pageRef: /portafolio/
  weight: 10
- name: Sobre Mi
  pageRef: /sobre-mi/
  weight: 10

footer:
  - name: Blog
    pageRef: /blog/
    weight: 10
  - name: Portafolio
    pageRef: /portafolio/
    weight: 10