main:
  - identifier: home
    name: Inicio
    pageRef: /
    weight: 10
  - identifier: categories
    name: Categorias
    pageRef: /categorias/
    parent: home
    weight: 1
  - identifier: tags
    name: Etiquetas
    pageRef: /etiquetas/
    parent: home
    weight: 2

  - identifier: about
    name: Sobre Mi
    pageRef: https://www.linkedin.com/in/dacadev/
    weight: 30

footer:
  - identifier: home
    name: Inicio
    pageRef: /
    weight: 10
  - identifier: about
    name: Sobre Mi
    pageRef: https://www.linkedin.com/in/dacadev/
    weight: 10
