main:
- name: Blog
  pageRef: /blog/
  weight: 10
- name: Sobre Mi
  pageRef: https://www.linkedin.com/in/dacadev/
  weight: 10

footer:
  - name: Blog
    pageRef: /blog/
    weight: 10
  - name: Sobre Mi
    pageRef: https://www.linkedin.com/in/dacadev/
    weight: 10